seed_everything: true
model:
  class_path: source.models.pair_models.CrossGATModel
  init_args:
    hidden_channels: 128
    num_gat_layers: 3
    num_inter_layers: 2
    num_egnn_layers: 3
    auxiliary_loss_weight: 0
    dropout: 0.01
    out_channels: 1
data:
  class_path: source.dataloader.pair_loader.ProteinPairDataModule
  init_args:
    root: data
    pdb_dir: data/raw # folder with PDB files
    pkl_dir: data/raw # folder with graphein .pkl files
    processed_dir_suffix: complex
    node_attr_columns:
      # - amino_acid_one_hot
      - meiler
      - expasy
      - hbond_acceptors
      - hbond_donors
      - sasa
      - rel_sasa
      - esm_embedding
    edge_attr_columns: null
    edge_kinds:
      - peptide_bonds
      - hydrophobic
      - ionic
      - distance_threshold
      - hbond
    use_surface: true
    batch_size: 32
    num_workers: 4
optimizer:
  class_path: torch.optim.Adam
  init_args:
    lr: 0.001
    weight_decay: 0.0001
trainer:
  logger:
    - class_path: pytorch_lightning.loggers.TensorBoardLogger
      init_args:
        save_dir: logs
        name: complex
        log_graph: false
  enable_checkpointing: true
  callbacks:
    - class_path: pytorch_lightning.callbacks.EarlyStopping
      init_args:
        patience: 5
        monitor: val_loss
        mode: min
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        save_top_k: 3
        monitor: val_loss
        mode: min
        filename: "{epoch:02d}-{val_loss:.2f}"
    - class_path: source.callbacks.LogMetrics
    - class_path: source.callbacks.LogDistances
    - class_path: source.callbacks.ClearOutputs
  enable_progress_bar: true
  max_epochs: -1
  log_every_n_steps: 1
  accelerator: auto
  strategy: auto
  precision: 32