seed_everything: true
model:
  class_path: source.models.single_models.CrossGATModel
  init_args:
    hidden_channels: 512
    num_gat_layers: 3
    num_inter_layers: 2
    num_egnn_layers: 3
    auxiliary_loss_weight: 0.1
    dropout: 0.05
    out_channels: 1
data:
  class_path: source.dataloader.single_loader.ProteinPairDataModule
  init_args:
    root: data # this should be J´s data folder... 
    pdb_dir: data/raw  
    batch_size: 32
    processed_dir_suffix: elias
    node_attr_columns: # change to include/exclude some kinds of node features
      - amino_acid_one_hot
      - b_factor
      - meiler
      - expasy
      - hbond_acceptors
      - hbond_donors
      - sasa
      - rel_sasa
      - esm_embedding
    edge_kinds: # change to include/exclude some kinds of edges
      - peptide_bonds
      - hydrophobic
      - ionic
      - distance_threshold
      - hbond
    sasa_threshold: 1   # its a Greater than ... and supposingly in Angström ? 
    num_workers: 8
optimizer:
  class_path: torch.optim.Adam
  init_args:
    lr: 0.0025
    weight_decay: 0.0001
trainer:
  logger:
    - class_path: pytorch_lightning.loggers.TensorBoardLogger
      init_args:
        save_dir: logs
        name: basic
        log_graph: true
  enable_checkpointing: true
  callbacks:
    - class_path: pytorch_lightning.callbacks.EarlyStopping
      init_args:
        patience: 5
        monitor: val_loss
        mode: min
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        save_top_k: 3
        monitor: val_loss
        mode: min
        filename: "{epoch:02d}-{val_loss:.2f}"
    - class_path: source.callbacks.LogParameters
    - class_path: source.callbacks.LogConfusionMatrix
    - class_path: source.callbacks.LogDistances
  enable_progress_bar: true
  max_epochs: -1
  log_every_n_steps: 1
  accelerator: gpu
  strategy: auto
  precision: 32  