seed_everything: true
model:
  class_path: source.models.pair_models.CrossGAT
  init_args:
    in_channels: 21
    out_channels: 2
    num_layers: 3
data:
  class_path: source.dataloader.pair_loader.ProteinPairDataModule
  init_args:
    root: /scicore/home/schwede/eberha0001/hackathon_data
    batch_size: 32
    num_workers: 4
optimizer:
  class_path: torch.optim.Adam
  init_args:
    lr: 0.001
    weight_decay: 0.0001
trainer:
  logger:
    - class_path: pytorch_lightning.loggers.TensorBoardLogger
      init_args:
        save_dir: logs
        name: basic
        log_graph: true
  enable_checkpointing: true
  callbacks:
    - class_path: pytorch_lightning.callbacks.EarlyStopping
      init_args:
        patience: 5
        monitor: hp_metric
        mode: min
    - class_path: source.callbacks.LogParametersCallback
  enable_progress_bar: true
  max_epochs: null
  log_every_n_steps: 1
  accelerator: gpu
  strategy: auto
  precision: 32