seed_everything: true
model:
  class_path: source.models.single_models.EGNNModel
  init_args:
    in_channels: 21
    num_layers: 3
    hidden_channels: 128
    out_channels: 1
    dropout: 0.01
data:
  class_path: source.dataloader.single_loader.ProteinDataModule
  init_args:
    root: data
    batch_size: 32
    num_workers: 4
optimizer:
  class_path: torch.optim.Adam
  init_args:
    lr: 0.001
    weight_decay: 0.0001
trainer:
  logger:
    - class_path: pytorch_lightning.loggers.TensorBoardLogger
      init_args:
        save_dir: logs
        name: basic
        log_graph: true
  enable_checkpointing: true
  callbacks:
    - class_path: pytorch_lightning.callbacks.EarlyStopping
      init_args:
        patience: 5
        monitor: val_loss
        mode: min
    - class_path: source.callbacks.LogParametersCallback
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        save_top_k: 3
        monitor: val_loss
        mode: min
        filename: "{epoch:02d}-{val_loss:.2f}"
  enable_progress_bar: true
  max_epochs: -1
  log_every_n_steps: 1
  accelerator: gpu
  strategy: auto
  precision: 32