seed_everything: true
model:
  class_path: source.models.pair_models.CrossGATModel
  init_args:
    in_channels: 21
    num_layers: 3
    out_channels: 1
data:
  class_path: source.dataloader.pair_loader.ProteinPairDataModule
  init_args:
    root: new_data
    pdb_dir: data/raw
    node_attr_columns:
      - amino_acid_one_hot
      - b_factor
    edge_attr_columns: null
    edge_kinds:
      - peptide_bonds
    sasa_threshold: null
    batch_size: 32
    num_workers: 4
optimizer:
  class_path: torch.optim.Adam
  init_args:
    lr: 0.001
    weight_decay: 0.0001
trainer:
  logger:
    - class_path: pytorch_lightning.loggers.TensorBoardLogger
      init_args:
        save_dir: logs
        name: basic
        log_graph: false
  enable_checkpointing: true
  callbacks:
    - class_path: pytorch_lightning.callbacks.EarlyStopping
      init_args:
        patience: 5
        monitor: val_loss
        mode: min
    - class_path: source.callbacks.LogParametersCallback
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        save_top_k: 3
        monitor: val_loss
        mode: min
        filename: "{epoch:02d}-{val_loss:.2f}"
  enable_progress_bar: true
  max_epochs: -1
  log_every_n_steps: 1
  accelerator: gpu
  strategy: auto
  precision: 32